/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bbanyai' at '4/17/18 8:52 AM' with Gradle 2.14.1
 *
 * @author bbanyai, @date 4/17/18 8:52 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
